 <div class="mobile-version">
 
    <div class="mobile-main-body">
    <div class="mobile-top-bar search-top-bar">
    	<div class="menu-icon">
    	<i class="icon-reorder icon-large user-menu-icon" ></i>
    	</div>
    	<div class="logo-service"><h2>全全服务</h2></div>
    </div>
    
    
     	<!-- start user -->
 	
 	<div class="management-menu hidden" id="management-menu"><ul>	  
 	   
 	   	  <li class="mobile-profile user-menu"><i style="color:#009900;" class="icon-home"></i><a style="color:#009900;" href="/index/index">返回首页</a></li>
 	   	  <li class="mobile-login user-menu "><i class="icon-user"></i><a href="/user/login">用户登入</a></li>
 	      <li class="mobile-mysearch user-menu"><i class="icon-search"></i><a href="/search/index">搜索</a></li>
 	      <li class="mobile-mypost user-menu"><i class="icon-pencil"></i><a href="">我的发布</a></li>
 	      <li class="mobile-mywatch user-menu"><i class="icon-star"></i><a href="">我的收藏</a></li>
 	      <li class="mobile-mysearch user-menu"><i class="icon-asterisk"></i><a href="">我的搜索</a></li>
 	      <li class="mobile-profile user-menu"><i class="icon-user"></i><a href="">个人信息</a></li>
 	      <li class="mobile-account user-menu"><i class="icon-cog"></i><a href="">账户管理</a></li>
 	      <li class="mobile-qqcenter user-menu"><i style="color:#ff66ff;" class="icon-heart"></i><a href="" style="color:#ff66ff;">服务前台</a></li>
 	   </ul>
 	   
 	   <p class="copyright">新西兰全全科技　版权所有（2015）</p>
 	   

 	</div>	
 	
 	<div class="management-menu-rec hidden"> </div>
 	
    <!-- end of start user -->	
    
   </div>
    
</div> <!-- end of mobile -->
       
       
       
       