<div class="postad-label">
post an ad
</div>
<div class="postad-container">
		<div class="postad-container1">
			<p class="postad-field1-word">Select a group</p>
			<b><hr style="margin-top:3px"></b>
			<div class="postad-field1" >
				<div class="postad-content">个人发布</div>
				<div class="postad-content">企业发布</div>
			</div>
		</div>
		<div class="postad-container2" style="display:none">
			<p class="postad-field2-word">Select a category</p>
			<!-- <span style="font-size:0.6em">Jobs</span> -->
			<hr class="postad-line">
			<div class="postad-field2">
				<div class="postad-content">工作</div>
				<div class="postad-content">餐饮</div>
				<div class="postad-content">住宿</div>
				<div class="postad-content">服务</div>
				<div class="postad-content">旅行</div>
				<div class="postad-content">娱乐</div>
				<div class="postad-content">企业</div>
				<div class="postad-content">商务</div>	
			</div>
		</div>
		<div class="postad-container3" style="display:none">
			<p class="postad-field3-word">Select a option</p>
			<hr class="postad-line">
			<div class="postad-field3">
				<div class="postad-content">工作</div>
				<div class="postad-content">餐饮</div>
				<div class="postad-content">住宿</div>
				<div class="postad-content">服务</div>
				<div class="postad-content">旅行</div>
				<div class="postad-content">娱乐</div>
				<div class="postad-content">企业</div>
				<div class="postad-content">商务</div>

			</div>
		</div>
		<div class="postad-container4" style="display:none">
			<p class="postad-field4-word">Select a option</p>
			<hr class="postad-line">
			<div class="postad-field4">
				<div class="postad-content">工作</div>
				<div class="postad-content">餐饮</div>
				<div class="postad-content">住宿</div>
				<div class="postad-content">服务</div>
				<div class="postad-content">旅行</div>
				<div class="postad-content">娱乐</div>
				<div class="postad-content">企业</div>
				<div class="postad-content">商务</div>
			</div>
		</div>
	
</div>