<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<meta http-equiv="Content-Type" content="text/html; charset=utf8" />
<title>新西兰全全网</title>
<meta name="description"  content="" />
<meta name="categorys" content="" />

<!--  
<link rel="stylesheet" href="/css/bootstrap.css">
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

-->
<link href="/css/style.css" rel="stylesheet">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>



 <script src="/js/ben.js"></script>
 <script src="/js/sheng.js"></script>
 <script src="/js/lei.js"></script>
 <link href="/css/ben.css" rel="stylesheet">
 <link href="/css/sheng.css" rel="stylesheet">
 <link href="/css/lei.css" rel="stylesheet">


</head>
 
 <div class="container-fluid" > 
  		<div class="container head_container">
					<div class="logo_bar">
						<div class="logo" > <img src="/images/logo.png" ></div>
						<div class="logo_comment">						
							<h3>全全网</h3>
						    <p class="logo_ad">Quickly find anything in NZ</p>
						</div>
					</div>
	
					<div class="top_nav_bar">
						<ul class="top_nav">
						        <li ><a class="" href="#">服务大全</a></li>
						        <li ><a href="#">首页</a></li>
						        <li ><a class="active" href="#" >工作</a></li> 
						        <li ><a href="#">商务</a></li> 
						        <li ><a href="#">留学</a></li> 
						        <li ><a href="#">旅行</a></li> 
						</ul>      
					</div>
				<div class="top_text_field">	
					<div class="top_search_bar">
					       <input class="top_search_field " type="text" value="" placeholder="搜索你需要的...">
					       <img class="top_search_button" src="/images/search-icon.png" />
					</div>
					<div class="top_post_bar">
					       <input class="top_post_button" type="text" disabled placeholder="免费发布">
					       <img class="top_post_icon" src="/images/post-icon.png" />
					</div>
				</div>
				
				<div class=" top_login_bar">
				     
				     <img class="top_login_icon" src="/images/login-icon.png" />
				     <div class="top_login_button">
				     <a href="" class="">登入</a>
					 <a href="" class="">注册</a>
					 </div>
				</div>
	
     </div>
    <div class="clearfix"></div>
 </div>
 

 

 <?php echo $this->layout()->content; ?>
 
</body>
</html>
