<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
 <link href="/css/bootstrap.3.1.1.css" rel="stylesheet">
 <script src="http://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>
 <script src="http://libs.baidu.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>  
<meta http-equiv="Content-Type" content="text/html; charset=utf8" />
<title>新西兰全全网</title>
<meta name="description"  content="" />
<meta name="categorys" content="" />
<link rel="stylesheet" href="/css/style.css" type="text/css">

<?php echo $this->headScript()->appendFile('/js/main.js');?>


</head>

<body>
<div class="head-container">

 <div class="head-banner">
   <div class="head width-1280">
   <div class="top-left">
     <div class="logo">
       <img src="/images/logo.png" style="height:80px;">
     </div>
     <div class="logo-reference">
        <p class="domain-name">QuanQuan.co.nz</p>
        <p class="reference-content">Quickly find anything in New Zealand</p>
     </div>
   </div>
   <div class="top-right">
    <div class="free-post-button"><a>免费发布</a></div>
    <ul>
       <li><a href="">登入</a><span>|</span></li>      
       <li><a href="">注册</a><span>|</span></li>
       <li><a href="">我的全全</a></li>
     </ul>
   </div>   
     
    </div> 
  </div>
  
  <div class="head-content width-1280">
    <div class="head-text">
      <div class="text-level1">
            <p>探索纽西兰</p>
            <p>从全全网开始</p>
      </div>
      <div class="text-level2"><p>Find anything in New Zealand, Quickly!</p></div>
    
    </div>
    <div class="head-nav">
      <div class="search-regions">
         <div class="map-icon"><img src="/images/map-icon.png" style="height:27px; margin:10px 0 0 15px;"></div>
         <div class="regions-drop-icon"><img src="/images/dropdown-icon.png" style="height:12px; margin:12px 0 0 15px;opacity:0.8"></div>
         
         
         <input readonly class="regions-input-nav" placeholder="请选择您需要的位置" value="" name="">
         <div class="regions-nav">
            <img src="/images/nav_bg.png" style="margin-top:-5px;" >
             <ul class="regions">
                <?php foreach ( $this->regions as $item ):?>
                   <?php 
                         $index=0;
                         foreach ($this->cities as $city){
                             if($city['region_id']==$item['region_id']){
                                 $index++;
                             }
                             if($index>1){
                                 break;
                             }
                         }                     
                      ?>
                   <li class="region-items">                  
                   <a  class="region-item" value="<?php echo $item['region_id'];?>"> <?php echo $item['name']; ?>                  
                                    
                   </a>
                   <?php if($index>1):?>
                       <img class='expend-icon' src="/images/plus-icon.png" data-swap='/images/minus-icon.png' style="height:25px; margin-top:5px; opacity:0.9; float:right; z-index:50;margin-right:15px;">
                   <?php endif;?> 
                   <?php if($index>1):?>
                      
                       <ul class="city-items"> 
                            <?php foreach( $this->cities as $city ): ?>                              
                                    <?php if($city['region_id']==$item['region_id']):?> 
                                      <li>                                                     
                                        <a  value="<?php echo $city['city_id'];?>" class="city-item">
                                             <?php echo $city['name']; ?>
                                        </a> 
                                       </li>                                    
                                     <?php endif;?>     
                             <?php endforeach;?>
                     </ul>    
                    
                   <?php endif;?>
                  </li>
                <?php endforeach;?> 
             </ul>
            </div>
                 
         
      </div>
      <div class="search-category">
        <div class="category-icon"><div class="map-icon"><img src="/images/category-icon.png" style="height:25px; margin:11px 0 0 10px;"></div></div>     
           <div class="category-drop-icon"><img src="/images/dropdown-icon.png" style="height:12px; margin:12px 0 0 15px; opacity:0.8"></div>   
           <div >   
         <input readonly class="category-input-nav" placeholder="请选择您需要的类别">
         <div class="category-nav hidden">  
             <ul class="category">
                <?php foreach ( $this->categories as $category ):?>
                   <li class="category-item">     
                    <a  class="item" value="<?php echo $category['category_id'];?>"> <?php echo $category['category_name']; ?> 
                       
                   </a>
                      <img class="category-expend-icon" src="/images/plus-icon.png" style="height:25px; margin-top:5px; opacity:0.9; float:right; margin-right:15px;">                   
                        
                    <ul class="sub-categories hidden">                
                    <?php foreach ($this->sub_categories as $sub_category):?>
                        
                            <?php 
                                 $index=0;
                                 foreach ($this->sub_sub_categories as $sub_sub_category){
                                     if($sub_sub_category['parent_category_id']==$sub_category['category_id']){
                                         $index++;
                                     }
                                     if($index>0){
                                         break;
                                     }
                                 }                     
                          ?>                      
                         <?php if($sub_category['parent_category_id']==$category['category_id']):?>
                           
                            
                            <li class="sub-category-item">
                            <a value="<?php echo $sub_category['category_id']; ?>" class="sub-category" ><?php echo $sub_category['category_name']; ?> 
                                                       
                            </a> 
                            <?php if($index>0):?>
                                 <img class="sub-category-expend-icon" src="/images/plus-icon.png" style="height:20px; margin-top:8px; opacity:0.9; float:right; margin-right:15px;">  
                             <?php endif;?> 
							 <?php if($index>0):?>
							         <ul class="sub-sub-categories ">                     
                                   <?php foreach ($this->sub_sub_categories as $sub_sub_category):?>                                      
                                         <?php if($sub_sub_category['parent_category_id']==$sub_category['category_id']):?>                                        
                                           <li class="sub-sub-category-item">
                                           <a value="<?php echo $sub_sub_category['category_id'];?>" class="sub-sub-category"><?php echo $sub_sub_category['category_name']; ?></a>
                                           </li>                                                                                                      
                                         <?php endif;?>                                      
                                  <?php endforeach;?>
                                   </ul>  
                             <?php endif;?>    
                        
                            </li>                                                                          
                         <?php endif;?>
                    <?php endforeach;?> 
                    </ul> 
                
                  </li>
                <?php endforeach;?> 
             </ul>
            </div>
       </div>   
                
      </div>
      <div class="search-icon"><img src="/images/search-icon.png" style="height:25px;  margin:11px 0 0 10px;"></div>

</div> 

</div>

<div class="fast-access width-1280">

   <div class="site-descrition">
   <h3>在 全全网</h3>
   <h3>你 可以找到生活所需的各类服务</h3>
   <br>
   <p>在这里</p>
   <p>发布和检索信息都是免费的</p>
   <p>我们致力于为在纽华人朋友提供优质的互联网服务</p>
   <p>并以此为荣</p>
   <p>欢迎给予建议</p>
   <p>让我们提供便佳服务</p>
   <br><br><br><br>
   <p class="text-bold">感谢你的来访</p>
   <p class="text-bold">祝nin在纽新兰生活愉快</p>
  </div>
  
  <div class="service-fast-access">
     <div>
      <h2 style="color:#fff;">在纽生活</h2>
     
     </div>
  </div>
  
  <div class="travel-fast-access"></div>

</div>

<div class="">



</div>

 <?php echo $this->layout()->content; ?>
 
 

</body>
</html>