<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf8" />
<title>新西兰全全网</title>
<meta name="description"  content="" />
<meta name="categorys" content="" />

<!--  
<link rel="stylesheet" href="/css/bootstrap.css">
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

-->
<link href="/css/style.css" rel="stylesheet">
<script src="/js/qq.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="/Font-Awesome-3.2.1/css/font-awesome.min.css">

<!--[if IE 7]>
<link rel="stylesheet" href="/Font-wesome-3.2.1/css/font-awesome-ie7.min.css">
<![endif]-->


<?php echo $this->headScript()->appendFile('http://code.jquery.com/jquery-1.11.3.min.js');?>

 <script src="/js/ben.js"></script>
 <script src="/js/sheng.js"></script>
 <script src="/js/lei.js"></script>
 <link href="/css/ben.css" rel="stylesheet">
 <link href="/css/sheng.css" rel="stylesheet">
 <link href="/css/lei.css" rel="stylesheet">

</head>
 <body>
 	<?php echo $this->layout()->content; ?>

 </body>

 </html>