 <div class="mobile-version">
 
    <div class="mobile-main-body">
    <div class="mobile-top-bar search-top-bar">
    	<div class="menu-icon">
    	<i class="icon-reorder icon-large user-menu-icon" ></i>
    	</div>
    	<div class="logo-service"><h2>搜索中心</h2></div>
    </div>
    
    
    
    
    
    <form class="content" method="post">

	    <div class="home-category text-field">            
	        <input type="text" name="category" class="custom-select select" value="" readonly="readonly"  placeholder="新西兰服务大全">
	        <i class="icon-columns  icon-select" ></i> 
	        <i class="icon-double-angle-right icon-large icon-gonext " ></i> 
	    </div>
	    <div class="home-keyword text-field">
	       <input type="text" name ="keyword" class="custom-input" type="text" placeholder="请输入关键词" value="">
	       <i class="icon-pencil icon-select " ></i> 
	    </div>
        <div class="home-category text-field">            
	        <input type="text" name="suborsubsubcategory" class="custom-select select category-select" placeholder="请选择服务类别" value=""  readonly="readonly">
	        <i class="icon-th-list  icon-select" ></i> 
	        <i class="icon-double-angle-right icon-large icon-gonext icon-category-select" ></i> 
	    </div> 
	   <div class="home-place text-field">            
	        <input type="text" name="cityortown" class="custom-select select place-select" placeholder="请选择城镇" value="">
	        <i class="icon-list-ol icon-select" ></i> 
	        <i class="icon-double-angle-right icon-large icon-gonext icon-place-select" ></i> 
	    </div> 

        <div class="home-submit text-field">
           <input type="text" name="submit" class="custom-select select submit-btn" value="查  询" readonly="readonly">
        </div>

 	</form>
 	
 	  
     <div class="home-reset text-field">
            <a class="home-reset-btn reset-btn" readonly="readonly">清除记录</a>
    </div>
 	
 	
 	<!-- start of category select option page -->
 	<div class="category-options hidden">
 	    <div class="mobile-top-bar category-top-bar">
	        	<div class="menu-icon">
    				<i class="icon-reorder icon-large user-menu-icon" ></i>
    			</div>
	    	<div class="logo-service"><h2>请选择类别</h2>
	    	  
	    	</div>
    	</div>
    	
    <div class="mobile-categories-list">
    	 <ul>
    	   <?php foreach ($this->subcategories as $item):?>
    	      <?php if($item['parent_id']=='104'):?>
 
		    	  <li class="mobile-sub-items">
		    	      <i class=" icon-heart" style="color:#; margin-right:2%;"></i>
		    	      <a class="mobile-sub-item" value="<?php echo $item['subcategory_id']?>" ><?php echo $item['subcategory_name']?></a> 
		    	      <i class=" icon-chevron-down icon-drowdownup" id="mobile-subcat-dwopdown"></i> 
		    	      <i class=" icon-chevron-up icon-drowdownup"  id="mobile-subcat-dwopup"  style="display: none;"></i>  
		    	      
		    	      <div class="m-sub-m hidden">
		    	      <ul class="mobile-sub-sub-categories " >
		    	       <li class="mobile-subsub-items"> 
		    	          <a class="mobile-subsub-item" value="0" >（所有）<?php echo $item['subcategory_name']?></a>
		    	       </li>
		    	      <?php foreach ($this->subsubcategories as $sub_item):?>
		    	                  
		    	              <?php if ($sub_item['parent_id']== $item['subcategory_id']):?>
		    	                  <li class="mobile-subsub-items"> 
		    	                    <a class="mobile-subsub-item" value="<?php echo $sub_item['subsubcategory_id'];?>" ><?php echo $sub_item['subsubcategory_name']?></a>
		    	                  </li>
		    	               <?php endif;?>
		    	      <?php endforeach;?>       
		    	      </ul>       
				     </div>       
		    	 </li>
	    	    
	    	     
    	     <?php endif;?>
    	   <?php endforeach;?>
    	  </ul>
    	
    	</div>
    </div><!-- end of category select option page -->
    
    <!-- start of place select option page -->
       	<div class="place-options hidden">
 	    <div class="mobile-top-bar place-top-bar">
	    	 <div class="menu-icon">
    				<i class="icon-reorder icon-large user-menu-icon" ></i>
    			</div>
    	<div class="logo-service"><h2>请选择城镇</h2>
    	  
    	</div>
        </div>
    
        <div class="mobile-place-list">
    	 <ul>
    	   <?php foreach ($this->regions as $region):?>
 
		    	  <li class="mobile-region-items">
		    	      <i class=" icon-heart" style="color:#; margin-right:2%;"></i>
		    	      <a class="mobile-region-item" value="<?php echo $region['region_id']?>" ><?php echo $region['region_name']?></a> 
		    	      <i class=" icon-chevron-down icon-drowdownup" id="mobile-region-dwopdown"></i> 
		    	      <i class=" icon-chevron-up icon-drowdownup"  id="mobile-region-dwopup"  style="display: none;"></i>  
		    	      
		    	      <div class="m-city-m hidden">
		    	      <ul class="mobile-city-categories " >
		    	       <li class="mobile-city-items"> 
		    	          <a class="mobile-city-item" value="0" ><?php echo $region['region_name']?>所有地区</a>
		    	       </li>
		    	      <?php foreach ($this->cities as $city):?>		    	                  
		    	              <?php if ($city['parent_id']== $region['region_id']):?>
		    	                  <li class="mobile-city-items"> 
		    	                    <a class="mobile-city-item" value="<?php echo $city['city_id'];?>" ><?php echo $city['city_name']?></a>
		    	                  </li>
		    	               <?php endif;?>
		    	      <?php endforeach;?>       
		    	      </ul>       
				     </div>       
		    	 </li>	    	   
    	   <?php endforeach;?>
    	  </ul>
    	
    	</div>
    
 	</div> <!-- end of place select option page -->
 	</div>
 	
 	
 	<!-- start user -->
 	
 	<div class="management-menu hidden" id="management-menu"><ul>	  
 	   
 	   	  <li class="mobile-profile user-menu"><i style="color:#009900;" class="icon-home"></i><a style="color:#009900;" href="/index/index">返回首页</a></li>
 	   	  <li class="mobile-login user-menu "><i class="icon-user"></i><a href="/user/login">用户登入</a></li>
 	      <li class="mobile-mysearch user-menu"><i class="icon-search"></i><a href="/search/index">搜索</a></li>
 	      <li class="mobile-mypost user-menu"><i class="icon-pencil"></i><a href="">我的发布</a></li>
 	      <li class="mobile-mywatch user-menu"><i class="icon-star"></i><a href="">我的收藏</a></li>
 	      <li class="mobile-mysearch user-menu"><i class="icon-asterisk"></i><a href="">我的搜索</a></li>
 	      <li class="mobile-profile user-menu"><i class="icon-user"></i><a href="">个人信息</a></li>
 	      <li class="mobile-account user-menu"><i class="icon-cog"></i><a href="">账户管理</a></li>
 	      <li class="mobile-qqcenter user-menu"><i style="color:#ff66ff;" class="icon-heart"></i><a href="" style="color:#ff66ff;">服务前台</a></li>
 	   </ul>
 	   
 	   <p class="copyright">新西兰全全科技　版权所有（2015）</p>
 	   

 	</div>	
 	
 	<div class="management-menu-rec hidden"> </div>
 	
 <!-- end of start user -->	
 	

   </div> <!-- end of mobile -->