<div class="mobile-version">
<div class="signup">

 	     <div class="mobile-top-bar register-top-bar">
	    	<div class="return-icon">
	    	  <a class="return-to-home-btn" href="/index/index">返回</a>
	    	</div>
	    	<div class="logo-service"><h2><i class="icon-user"> </i> 注册成为会员</h2>
	    	    
	    	</div>
	     </div>	     
</div>

    <div style="text-align: center; margin-top:80px;">
    
       <p style="color:#001f4d;">您的账号已激活成功</p>
       <p style="color:red; line-height:40px;">现在</p>
       <p style="color:#001f4d;">您可以在全全网发布信息</p>
       <p style="color:#001f4d;">感谢您的支持，祝您愉快</p>
    </div>


</div>



<!-- below for desktop -->