<div class="mobile-version">
<div class="signup">

 	     <div class="mobile-top-bar register-top-bar">
	    	<div class="return-icon">
	    	  <a class="return-to-home-btn" href="/index/index">首页</a>
	    	</div>
	    	<div class="logo-service"><h2><i class="icon-user"> </i> 注册成为会员</h2>
	    	    
	    	</div>
	     </div>	
	     
	    
	     
</div>

    <div style="text-align: center; margin-top:80px;">
    
       <p style="color:#001f4d;">您的账号已注册成功</p>
       <p style="color:red; line-height:40px;">下一步</p>
       <p style="color:#001f4d;">请在24小时内到您的注册邮箱，激活账号</p>
    
    </div>


</div>

