
<div class="postad-alertcontainer">
</div>
<div class="postad-alert">
<div class="postad-closedialog">
<img class="postad-close"src="/images/iconfont-clear (2).png">
</div>
<img src="/images/iconfont-gantanhao (1).png" class="postad-alertimg">
<div class="postad-alerttext">
<p>你输入的<span class="postad-inputalert"></span>有误<span style="font-size:20px"><b>!!!</b></span></p>
</div>
<div class="postad-alterbox">重新输入</div>

</div>
<div class="postad-label">
编写信息详情
</div >
<form>
<div class="container postad-container" style="height:800px;">
	<header class="postad-title">机构信息:</header>
		<div class="postad-text">
			<div class="postad-word">公司名称:</div>
			<div class="postad-word"> 区域:</div>
			<div class="postad-word">城市:</div>
			<div class="postad-word">城镇:</div>
			<div class="postad-word"style="margin-top:35px">电话号码:</div>
			<div class="postad-word"> 手机:</div>
			<div class="postad-word" style="margin-top:200px">公司简介:</div>
		</div>
		<div class="postad-box">
			<input type="text" name="company" id="postad-company"class="postad-input  "required>
			<span class="postad-warn">你输入有误</span><br>
			<select class="postad-input postad-region"name="region" style="width:54%">
			<option value="-1"style="display:none">请先选择区域</option>
			<?php foreach ($this->regions as $item):?>
			<option value="<?php echo $item['region_id'] ?>"><?php echo $item['region_name'] ?></option>
  			<?php endforeach;?>
		</select><span style="margin-left:20px" class="postad-warn postad-warntoregion">请输入区域</span><br>
			<select style="width:54%;"class="postad-input postad-city"name="city" required>
  		</select><span class="postad-warnregion">请先输入区域</span><span style="margin-left:20px" class="postad-warn postad-warntocity">请输入城市</span><br>
			<select style="width:54%;margin-bottom: 20px"class="postad-input postad-town"name="town"required>
	  	</select><span class="postad-warncity">请先输入城市</span><span class="postad-townforcity">
	  	请先输入区域</span><span style="margin-left:20px" class="postad-warn postad-warntotown">请输入城镇</span><br>
	  	<input name="phone"class="postad-input"id="postad-phone"  type="text" style="margin-top:-5px;" placeholder="请输入有效号码"required ><span class="postad-warn">你输入有误</span><br>
			<input  placeholder="请输入有效号码" id="postad-mobile"class="postad-input" type="text" name="mobile"style="margin-bottom: 70px"required ><span class="postad-warn">你输入有误</span><br>
			
	  	<textarea id="postad-summary"class="postad-input postad-txtarea" name="company-summary" required></textarea>
			<span class="postad-warn" style="margin-top:10px">请输入公司简介</span><br>
		</div>
		<div class="postad-text">
			<div class="postad-word">是否显示号码:</div>
			<div class="postad-word">邮箱地址:</div>
			<div class="postad-word">公司标签:</div>
			
		</div>
		<div class="postad-box">
			<input class="postad-checkbox" id="postad-checknum"style="margin-top:9%"type="checkbox"  name="ifshowphone"checked="true"required/><br>
			<input class="postad-input" id="postad-email"type="email" name="e-mail"required><span class="postad-warn">你输入有误</span><br>
			<a class="postad-file">选择标签<input type="file" name="logo" id="postad-loadimg"></a>
			<img id="postad-showimg"></img>
			
			<div  class="postad-showimage">请选择图片</div >
			<div  class="postad-warn  postad-warnrightimg" style="margin-top:25px">请选择正确的图片格式</div >
			<div  class="postad-warn postad-successimg"><img src="/images/start-icon.png" style="margin-top:2px"><p style="margin-top:-38px;margin-left:50px">成功添加图片</p></div ><br>
		</div>
</div>
<div class="container postad-container" style="height:320px;">
<header class="postad-title">招聘福利与其他:</header>
	<div class="postad-text">
		<div class="postad-word">工作标题:</div>
		<div class="postad-word">支付种类:</div>
		<div class="postad-word">工资:</div>
	</div>
	<div class="postad-box">
		
			<input type="text" class="postad-input" id="postad-title"name="title" required><span class="postad-warn">你输入有误</span><br>
			<select  name="pay-type"class="postad-input postad-paytype" style="width:54%" required>
				<option value="-1" style="display:none">先选择种类再选择工资</option>
				<option value="1" >时薪</option>
				<option value="2" >年薪</option>
				<option value="3">其他</option>
			</select><span class="postad-warnwage1">请选择工作种类</span><br>

			<select  name="allowance"id="postad-allowance1"class="postad-input postad-allowance " style="width:26%;"required>
				
			</select>
			<span class="postad-to">To</span>
			<select  name="allowance"class="postad-input postad-allowance" id="postad-allowance2" style="width:26%;"required>
			</select><br>
			<p class="postad-warnwage">请先选择工作种类</p>
			<p class="postad-selwage1">请选择工资</p>
			<p class="postad-selwage2" style="margin-left:130px">请选择工资</p>
	</div>
	<div class="postad-text">
		<div class="postad-word">需要人数:</div>
		<div class="postad-word">工作种类:</div>
		
	</div>
	<div class="postad-box">

			<input type="number"placeholder="请输入大于0的整数" id="postad-numreq"name="num-required"min="1" class="postad-input" required><span class="postad-warn">你输入有误</span><br>
			<select  name="job-type"id="postad-jobtype"class="postad-input"style="width:54%"required>
				<option value="-1" style="display:none">请选择工作种类</option>
				<option value="1">全职</option>
				<option value="2">兼职</option>
				<option value="3">合同</option>
				<option value="4">其他</option>
			</select><span class="postad-warn">你输入有误</span><br>
			
	</div>
</div>
<div class="container postad-container" style="height:600px;">
	<header class="postad-title">招聘需求:</header>
	<div class="postad-text">
		<div class="postad-word">拥有工签:</div>
		<div class="postad-word"style="margin-top:18px">工作经验:</div>
		<div class="postad-word"style="margin-top:40px"> 学历:</div>
		<div class="postad-word"style="margin-top:170px">需求:</div>
		
	</div>
	<div class="postad-box" style="margin-top:10px">
			<input type="checkbox" checked="true" class="postad-checkbox" name="work-visa" style="margin-top:5%" required><br>
			
			<select name="experience"id="postad-experience" class="postad-input" style="width:54%;margin-bottom: 20px"required>
			<option value="-1" style="display: none">请选择工作经验</option>
			<option value="1">实习生</option>
			<option value="2">1-2年</option>
			<option value="3">3-5年</option>
			<option value="4">5-10年</option>
			<option value="5">10年以上</option>
			</select> <span class="postad-warn">你还没有输入</span><br>
			<select name="qualification" id="postad-qua"class="postad-input">
			<option value="-1"style="display:none">请选择学历</option>
			<option value="1">不限</option>
			<option value="2">高中/中专</option>
			<option value="3">大专</option>
			<option value="4">本科</option>
			<option value="5">研究生以上</option>
			</select><span class="postad-warn">你还没有输入学历</span><br>
			<textarea class="postad-input postad-txtarea" name="requirement"id="postad-requirement" style="margin-top:10px"required></textarea>
			<div class="postad-warn"style="margin:22px 0px;"><span style="margin-left:20px">你输入有误
			</span></div><br>
	</div>
	<div class="postad-text">
		<div class="postad-word">性别:</div>
		<div class="postad-word"> 语言:</div>
		
	</div>
			<div class="postad-box">
			<div class="postad-inputnoshadow">
			<p class="postad-textmale">男</p>
			<input type="radio" name="gender"value="1"id="postad-male"required>
			<p class="postad-textfemale">女</p>
			<input type="radio" name="gender"value="2"id="postad-female"required>
			<span class="postad-warn">你还没有输入性别</span>
			</div>
			<div class="postad-inputnoshadow" style="margin-top:13px">
			<p class="postad-language" style="margin-left:0px;">中文</p><input type="checkbox" class="postad-checkbox" name="language"value="1"checked="true" style="float:left">
			<p class="postad-language">英文</p><input type="checkbox" class="postad-checkbox"name="language"value="2"style="float:left">
			<p class="postad-language">其他</p><input type="checkbox" class="postad-checkbox"name="language"value="3"style="float:left">
			</div>
			
	</div>
</div>
<div class="postad-label postad-button">保存</div>

</form>
